//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfSer4
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcceptanceSet
    {
        public int Id { get; set; }
        public bool IsAcceptEmailSent { get; set; }
        public Nullable<System.DateTime> AcceptEmailDate { get; set; }
        public string AuthReqCode { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string AuthCode { get; set; }
        public int Account_Id { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
