//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfSer4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WcfDSUsersEntities : DbContext
    {
        public WcfDSUsersEntities()
            : base("name=WcfDSUsersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {

            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcceptanceSet> AcceptanceSets { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
    }
}
